name: Check Commit Message
on: [pull_request]

jobs:
  check-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Commit Message
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})
          commit_regex='^[A-Z]+-[0-9]+ .+'
          if ! [[ ${commit_message} =~ ${commit_regex} ]]; then
            echo "Your commit message must follow the convention: 'JIRA-1234 commit message', where JIRA is your Jira issue prefix."
            exit 1
          fi